[features]
resolution = true
skip-lint = false

[programs.localnet]
treasury_escrow = "11111111111111111111111111111111"

[programs.devnet]
treasury_escrow = "6GabEnTZtPMyUDkrbzEMDktDupZ3gxVWb6oEHBsoRZ61"

[programs.mainnet]
treasury_escrow = "6GabEnTZtPMyUDkrbzEMDktDupZ3gxVWb6oEHBsoRZ61"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/launch.json"

[toolchain]
anchor_version = "0.31.1"

# IDL generation settings
[build]
idl = "target/idl"
type = "anchor"
readme = true
no-docs = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# To clone accounts for local tests, use array-of-tables syntax like:
# [[test.validator.clone]]
# address = "<account_pubkey>"

